spring:
  config:
    activate:
      on-profile: "prod"


build:
  version: "1.8"

accounts:
  message: "Welcome to accounts PROD APIs"
  contactDetails:
    name: "Shamil-Prod"
    email: "samilheyderovprod2003@gmail.com"
  onCallSupport:
    -(+994)-44-444-44-44
    -(+994)-22-222-22-22